services:
  datadog:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DATADOG_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_LOGS_ENABLED=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - spring-net

  apigateway:
    build:
      context: .
      dockerfile: apigateway/Dockerfile
    container_name: apigateway
    ports:
      - "8085:8080"
    depends_on:
      - eureka-server
    networks:
      - spring-net

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: eureka
    ports:
      - "8761:8761"
    networks:
      - spring-net

  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-net

  professor-service:
    build:
      context: .
      dockerfile: professor-service/Dockerfile
    container_name: professor-service
    ports:
      - "8081:8080"
    depends_on:
      - datagateway
      - eureka-server
    networks:
      - spring-net

  admin-service:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    container_name: admin-service
    ports:
      - "8082:8080"
    depends_on:
      - datagateway
      - eureka-server
    networks:
      - spring-net

  datagateway:
    build:
      context: .
      dockerfile: datagateway/Dockerfile
    container_name: datagateway
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_PROFILES_ACTIVE=docker
      - PROFESSOR_SERVICE_URL=http://professor-service:8080
      - ADMIN_SERVICE_URL=http://admin-service:8080
    ports:
      - "8080:8080"
    depends_on:
      - db
      - eureka-server
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  postgres_data:
