services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: closedsarc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  professor-service:
    build:
      context: .
      dockerfile: professor-service/Dockerfile
    container_name: professor-service
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - spring-net

  admin-service:
    build:
      context: .
      dockerfile: admin-service/Dockerfile
    container_name: admin-service
    ports:
      - "8082:8080"
    depends_on:
      - db
    networks:
      - spring-net

  datagateway:
    build:
      context: .
      dockerfile: datagateway/Dockerfile
    container_name: datagateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - PROFESSOR_SERVICE_URL=http://professor-service:8080
      - ADMIN_SERVICE_URL=http://admin-service:8080
    ports:
      - "8080:8080"
    depends_on:
      - professor-service
      - admin-service
    networks:
      - spring-net

networks:
  spring-net:

volumes:
  postgres_data:
