sonar.projectKey=admin-service
sonar.projectName=Admin Service
sonar.host.url=http://localhost:9000
sonar.login=squ_af576242d84f07284e4f6f355dba10482946d147
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
