server:
  port: 8085

management:
  datadog:
    metrics:
      export:
        apiKey: ${DATADOG_API_KEY}
        uri: https://api.datadoghq.com
        step: 10s

spring:
  application:
    name: apigateway

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        prefer-ip-address: true

    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        # ADMIN SERVICE
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        # PROFESSOR SERVICE
        - id: professor-service
          uri: lb://professor-service
          predicates:
            - Path=/professor/**
          filters:
            - StripPrefix=1
